### PR TITLE
remix www.youtube.com/@BBestian's freemath latest video and embeded on freemath's homepage

### PR DESCRIPTION
**Pull request by leechiuhui**
1.Remix the latest freemath video from [www.youtube.com/@BBestian](http://www.youtube.com/@BBestian)  channel and embed it on the freemath homepage(new.vue).
2.The embed code in new.vue may need to be updated to link to the [www.youtube.com/@BBestian](http://www.youtube.com/@BBestian) channel.I have uploaded the remixed videos for reference.
3.updated embed youtube width?&height 
截圖 2024-06-11 上午7 22 29

### CODE REVIEW

**Comment by bestian** [comment]
Thank for the vedio, but indeed, Freemath Project is not only owned by me, but by 朱佳仁&唐宗浩

**Comment by bestian** [comment]
影音可以先放上促進會官網的"相關影音"
而非Freemath首頁

https://sites.google.com/d/0B-3AeNXITt7ZbDRsTlNpM3FrY1k/p/12gAUv3iUzilYujzE3XqOAKlDlO2mu-3O/edit?resourcekey=0-9hkveYhGjbxQ9iNuR8hltA

**Comment by bestian** [comment]
@leechiuhui 

can you paste your remixed vedio's YouTube Link 在原影片的留言區?

https://www.youtube.com/watch?v=Hnmtv4TKBtc

**Comment by leechiuhui** [comment]
抱歉啊，
目前影片已經更新了，把人名拿掉，remixed youtube新網址已經改為https://youtu.be/As0xp6f4dlw?si=f-pvnBGK_hu1ozUB
截圖 2024-06-11 上午8 53 04，也已經留言。
另此前的youtube位址影片已經拿掉，會無法連結。

**Comment by leechiuhui** [comment]
> 影音可以先放上促進會官網的"相關影音" 而非Freemath首頁
> 
> https://sites.google.com/d/0B-3AeNXITt7ZbDRsTlNpM3FrY1k/p/12gAUv3iUzilYujzE3XqOAKlDlO2mu-3O/edit?resourcekey=0-9hkveYhGjbxQ9iNuR8hltA
已放連結，連到remixed的頻道
截圖 2024-06-11 上午9 02 01

**Pull request closed without merging**
